inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ControlPointDemo'

pod 'upnpx', :git => 'https://github.com/fkuehne/upnpx.git', :commit => '8e31bd182d7e7b4cb07220cab2b627a5653792e6'
pod 'AFNetworking', '2.5.0'
pod 'CocoaHTTPServer', '2.3'
pod 'Ono', '1.2.0'
