inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ControlPointDemo'

pod 'upnpx', :git => 'https://github.com/fkuehne/upnpx.git', :commit => '5228d90c4fcd5aa5a92cbd3ca7ad4a91cbcabc98'