inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

project 'ControlPointDemo'

target 'ControlPointDemo' do
	pod 'UPnAtom', :path => '../..'
	pod 'Ono', :git => 'https://github.com/master-nevi/Ono.git'
end
